apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  namespace: blog-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
        - name: blog-frontend
          image: 341931614219.dkr.ecr.ap-northeast-2.amazonaws.com/blog-frontend:9a945b37
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: blog-frontend