apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: blog-frontend
  namespace: blog-app
stringData:
  AWS_ACCESS_KEY_ID: access_key
  AWS_SECRET_ACCESS_KEY: secret_key
  AWS_DEFAULT_REGION: ap-northeast-2