apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  namespace: blog-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
        - name: blog-frontend
          image: ${{ secrets.AWS_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/blog-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80